CREATE TABLE IF NOT EXISTS user (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(16) NOT NULL,
    email VARCHAR(255) NOT NULL,
    pass VARCHAR(255) NOT NULL,
    exp INT UNSIGNED NOT NULL DEFAULT 0,
    campaign INT UNSIGNED NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT name_unique UNIQUE (name),
    CONSTRAINT email_unique UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS unit_type (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(32) NOT NULL,

    CONSTRAINT name_unique UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS unit_template (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    type_id INT UNSIGNED NOT NULL,
    name VARCHAR(32) NOT NULL,
    hp SMALLINT UNSIGNED NOT NULL CHECK (hp > 0),
    atk SMALLINT UNSIGNED NOT NULL CHECK (atk > 0),
    def SMALLINT UNSIGNED NOT NULL CHECK (def > 0),
    spd SMALLINT UNSIGNED NOT NULL CHECK (spd > 0),

    CONSTRAINT name_unique UNIQUE (name),
    FOREIGN KEY (type_id) REFERENCES unit_type(id) ON UPDATE CASCADE ON DELETE CASCADE
);
