version: "3.8"
services:
  idlemon:
    build:
      context: .
    environment:
      - ENV=${ENV}
      - PORT=${PORT}
      - CLIENT_VERSION=${CLIENT_VERSION}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - CREATE_TABLES=${CREATE_TABLES}
      - DROP_TABLES=${DROP_TABLES}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASS=${ADMIN_PASS}
      - INSERT_ADMIN=${INSERT_ADMIN}
    restart: always
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:6-alpine
    restart: always
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DATABASE=${DB_NAME}
    restart: always
  nginx:
    image: nginx:alpine
    ports:
      - "80:${PORT}"
    restart: always
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
